import fs from 'node:fs';
import { ANALYSED_FILE } from './constants.mjs';

export function loadAnalysedCases() {
  const analysed = new Set();
  if (!fs.existsSync(ANALYSED_FILE)) return analysed;

  const content = fs.readFileSync(ANALYSED_FILE, 'utf8');
  for (const line of content.split('\n')) {
    const match = line.match(/^-\s+(\w+_\w+):/);
    if (match) analysed.add(match[1]);
  }
  return analysed;
}

export function recordAnalysedCase(caseId, result, details) {
  const line = `- ${caseId}: ${result} (${details})\n`;
  if (!fs.existsSync(ANALYSED_FILE)) {
    fs.writeFileSync(ANALYSED_FILE, '# Analysed Cases\n\nGenerated by bugsAutoDiscovery.mjs\n\n');
  }
  fs.appendFileSync(ANALYSED_FILE, line);
}

