import fs from 'node:fs';
import { ANALYSED_FILE } from './constants.mjs';

export function loadAnalysedCases() {
  const analysed = new Set();
  if (!fs.existsSync(ANALYSED_FILE)) return analysed;

  const content = fs.readFileSync(ANALYSED_FILE, 'utf8');
  for (const line of content.split('\n')) {
    const match = line.match(/^-\s+(\w+_\w+):\s+([A-Z()]+)\s+\(/);
    if (!match) continue;
    const [, caseId, result] = match;
    // Allow re-processing old SKIP entries after capability improvements.
    if (result === 'SKIP') continue;
    analysed.add(caseId);
  }
  return analysed;
}

export function recordAnalysedCase(caseId, result, details) {
  const line = `- ${caseId}: ${result} (${details})\n`;
  if (!fs.existsSync(ANALYSED_FILE)) {
    fs.writeFileSync(ANALYSED_FILE, '# Analysed Cases\n\nGenerated by autoDiscovery/runAutodiscoveryAgent.mjs\n\n');
  }
  fs.appendFileSync(ANALYSED_FILE, line);
}
